---
- name: Transferir arquivo JSON do Windows para o servidor Ansible
  hosts: windows
  tasks:
    - name: Copiar arquivo JSON do Windows para o Ansible
      win_copy:
        src: C:\Users\Miguel-teste\inventario_completo.json
        dest: /home/micro11/teste
