- name: Criar diretório com permissões de root
  ansible.builtin.file:
    path: "/home/micro11/teste"
    state: directory
    mode: '0755'
  become: true

- name: Transferir arquivo JSON
  ansible.builtin.fetch:
    src: "C:\\Users\\Miguel-teste\\inventario_completo.json"
    dest: "/home/micro11/teste/inventario_completo.json"
    flat: yes
  become: true
