---
- name: Transferir arquivo JSON do Windows para o servidor Ansible
  hosts: all
  become: false
  vars:
    myfile: 'C:\Users\Miguel-teste\inventario_completo.json'
    dump_dir: "\teste\"
  tasks:
    - name: fetch file
      ansible.builtin.fetch:
        src: "{{ myfile }}"
        dest: "{{ dump_dir }}"
