- name: Transferir arquivo JSON do Windows para o servidor Ansible
  hosts: all
  become: false
  vars:
    myfile: 'C:\Users\Miguel-teste\inventario_completo.json'
    dest_path: "/teste/inventario_completo.json"
  tasks:
    - name: Transferir arquivo JSON
      ansible.builtin.fetch:
        src: "{{ myfile }}"
        dest: "{{ dest_path }}"
        flat: yes
