---
- name: Pesquisar AssinadorARISP.exe na pasta Downloads e gerar relatório
  hosts: all
  gather_facts: no
  tasks:
    - name: Criar diretório C:\Temp se não existir
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Procurar caminho da pasta Downloads
      win_shell: |
        $shell = New-Object -ComObject Shell.Application
        $downloads = $shell.Namespace('shell:::{374DE290-123F-4565-9164-39C4925E467B}').Self.Path
        $downloads
      register: downloads_folder

    - name: Procurar AssinadorARISP.exe na pasta Downloads
      win_find:
        paths: "{{ downloads_folder.stdout }}"  # Usando o caminho obtido do PowerShell
        patterns: "AssinadorARISP.exe"
        recurse: yes
      register: found_files

    - name: Gerar relatório se o AssinadorARISP.exe for encontrado
      win_lineinfile:
        path: "C:\\Temp\\relatorio_assinadorarisp.txt"
        line: "{{ inventory_hostname }} tem o AssinadorARISP.exe"
        create: yes
      when: found_files.files | length > 0

    - name: Gerar relatório se o AssinadorARISP.exe não for encontrado
      win_lineinfile:
        path: "C:\\Temp\\relatorio_assinadorarisp.txt"
        line: "{{ inventory_hostname }} NÃO tem o AssinadorARISP.exe"
        create: yes
      when: found_files.files | length == 0

    - name: Fetch do relatório para o servidor
      ansible.builtin.fetch:
        src: "C:\\Temp\\relatorio_assinadorarisp.txt"  # Caminho no Windows
        dest: "/tmp/relatorio_{{ inventory_hostname }}.txt"  # Caminho no servidor Linux
        flat: yes
