---
- name: Baixar e instalar atualizações do Windows com reinícios
  hosts: windows
  gather_facts: false
  tasks:

    - name: Baixar as atualizações do Windows (sem instalar)
      ansible.windows.win_updates:
        category_names: '*'
        state: downloaded

    - name: Reiniciar após o download das atualizações
      ansible.windows.win_reboot:
      when: ansible_windows_update.downloaded > 0  # Reinicia apenas se houver atualizações baixadas

    - name: Instalar as atualizações baixadas e reiniciar se necessário
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
