---
- name: Atualizar Windows via Windows Update
  hosts: windows
  gather_facts: false
  tasks:
    - name: Baixar e instalar todas as atualizações de segurança
      ansible.windows.win_updates:
        state: installed
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: true
      register: update_results

    - name: Exibir o resultado das atualizações aplicadas
      debug:
        var: update_results
