---
- name: Copiar e executar o arquivo .exe
  hosts: windows
  tasks:
    - name: Copiar o arquivo .exe para o diretório /tmp do host
      ansible.builtin.copy:
        src: /home/micro11/aaaaaaa.exe
        dest: C:\Windows\Temp\aaaaaaa.exe

    - name: Executar o arquivo .exe
      win_command: C:\Windows\Temp\aaaaaaa.exe
