---
- name: Remover certificados expirados
  hosts: windows
  tasks:
    - name: Remover certificados expirados
      win_shell: |
        $expired = Get-ChildItem cert:\CurrentUser\My | Where-Object { $_.NotAfter -lt (Get-Date) }
        $expired | ForEach-Object { Remove-Item $_.PSPath -Force }
