---
- name: Remover todos os certificados dos hosts Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Obter todos os certificados armazenados
      win_certificate_store:
        store_name: "My"
        state: "list"
      register: certs

    - name: Remover os certificados
      win_certificate_store:
        store_name: "My"
        thumbprint: "{{ item.thumbprint }}"
        state: "absent"
      loop: "{{ certs.certificates }}"
      when: certs.certificates is defined
