---
- name: Remover todos os certificados dos hosts Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Remover certificados do armazenamento "My"
      win_certificate_store:
        store_name: "My"
        state: "absent"
        thumbprint: "{{ item.thumbprint }}"
      loop: "{{ query('win_certificate', store_name='My') }}"
      when: query('win_certificate', store_name='My') is defined
