---
- name: Remover todos os certificados de hosts Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Remover certificados do CurrentUser\My
      win_shell: |
        Start-Process powershell -ArgumentList "Get-ChildItem -Path Cert:\CurrentUser\My | ForEach-Object { Remove-Item $_.PSPath -Force }" -Verb RunAs
      become: true
      become_user: TI

    - name: Remover certificados do LocalMachine\My
      win_shell: |
        Start-Process powershell -ArgumentList "Get-ChildItem -Path Cert:\LocalMachine\My | ForEach-Object { Remove-Item $_.PSPath -Force }" -Verb RunAs
      become: true
      become_user: TI
