- name: Remover certificados expirados em máquinas Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Remover certificados expirados do usuário atual
      ansible.builtin.win_powershell:
        script: |
          $certificates = Get-ChildItem Cert:\CurrentUser\My
          foreach ($cert in $certificates) {
              if ($cert.NotAfter -lt (Get-Date)) {
                  Remove-Item -Path "Cert:\CurrentUser\My\$($cert.Thumbprint)" -Force
              }
          }

    - name: Remover certificados expirados do LocalMachine
      ansible.builtin.win_powershell:
        script: |
          $certificates = Get-ChildItem Cert:\LocalMachine\My
          foreach ($cert in $certificates) {
              if ($cert.NotAfter -lt (Get-Date)) {
                  Remove-Item -Path "Cert:\LocalMachine\My\$($cert.Thumbprint)" -Force
              }
          }
