---
- name: Remover todos os certificados do armazenamento pessoal (CurrentUser\My)
  hosts: windows
  gather_facts: no
  tasks:
    - name: Obter lista de thumbprints dos certificados do armazenamento CurrentUser\My
      win_shell: |
        $certs = Get-ChildItem -Path Cert:\CurrentUser\My
        $certs | Select-Object -ExpandProperty Thumbprint
      register: cert_thumbprints_current_user_my

    - name: Verificar thumbprints coletados
      debug:
        var: cert_thumbprints_current_user_my.stdout_lines

    - name: Remover todos os certificados do armazenamento CurrentUser\My
      win_certificate_store:
        store_name: "My"
        thumbprint: "{{ item }}"
        state: "absent"
      loop: "{{ cert_thumbprints_current_user_my.stdout_lines }}"
      when: cert_thumbprints_current_user_my.stdout_lines | length > 0
