---
- name: Remover todos os certificados dos hosts Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Obter informações sobre os certificados
      win_certificate_facts:

    - name: Remover todos os certificados
      win_certificate_store:
        store_name: "My"
        thumbprint: "{{ item.thumbprint }}"
        state: "absent"
      loop: "{{ ansible_facts.certificates }}"
      when: ansible_facts.certificates is defined
