---
- name: Remover todos os certificados dos hosts Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Obter lista de thumbprints dos certificados
      win_shell: |
        $certs = Get-ChildItem -Path Cert:\CurrentUser\My
        $certs | Select-Object -ExpandProperty Thumbprint
      register: cert_thumbprints

    - name: Remover todos os certificados
      win_certificate_store:
        store_name: "My"
        thumbprint: "{{ item }}"
        state: "absent"
      loop: "{{ cert_thumbprints.stdout_lines }}"
      when: cert_thumbprints.stdout_lines | length > 0
