---
- name: Coletar chaves do Windows das máquinas
  hosts: windows
  tasks:
    - name: Copiar script VBScript para as máquinas
      win_copy:
        src: /home/micro11/Script/chave_windows.vbs
        dest: C:\Windows\chave_windows.vbs

    - name: Executar script com credenciais usando runas
      win_shell: |
        Start-Process "runas.exe" -ArgumentList "/user:teste 'cscript.exe C:\Windows\chave_windows.vbs'"
