---
- name: Coletar chaves do Windows das máquinas
  hosts: windows
  tasks:
    - name: Copiar script VBScript para as máquinas
      win_copy:
        src: /home/micro11/Script/chave_windows.vbs
        dest: C:\Windows\chave_windows.vbs

    - name: Executar script com credenciais
      win_shell: |
        $securePassword = ConvertTo-SecureString "Sc4lc0*" -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential("teste", $securePassword)
        Start-Process "C:\Windows\System32\cscript.exe" -ArgumentList "C:\Windows\chave_windows.vbs" -Credential $cred
