---
- name: Copiar arquivo do servidor Ansible para o host Windows
  hosts: windows
  tasks:
    - name: Transferir arquivo para o host Windows
      win_copy:
        src: /teste/oi.txt
        dest: C:\Users\Miguel-teste\Downloads\oi
