---
- name: Coletar chaves do Windows das máquinas
  hosts: windows  # Grupo de hosts no seu inventário
  tasks:
    - name: Copiar script VBScript para as máquinas
      win_copy:
        src: \Script\chave_windows.vbs
        dest: C:\Windows\chave_windows.vbs

    - name: Coletar arquivos gerados
      fetch:
        src: C:\Windows\chave_windows.txt
        dest: /home/micro11/Empresas
        flat: yes  # Mantém apenas os arquivos sem subpastas

- name: Consolidar chaves em um único CSV
  hosts: localhost
  tasks:
    - name: Criar arquivo CSV consolidado
      shell: |
        echo "Nome do Computador;Chave do Windows" > chaves.csv
        cat chaves/* >> chaves.csv
