---
- name: Executar script Python no Windows
  hosts: windows
  become: yes
  become_user: TI  # Se necessário para o acesso
  tasks:
    - name: Executar script Python
      win_command: python C:\Windows\Temp\script.py
