---
- name: Copiar arquivo do servidor para o host Windows
  hosts: windows
  tasks:
    - name: Copiar o arquivo para o host Windows
      win_copy:
        src: /teste/teste.exe
        dest: C:\Users\Miguel-teste\Downloads\teste.exe  # Caminho de destino no Windows
