---
- name: Executar script Python no Windows
  hosts: seus_hosts_windows
  become: yes
  become_user: TI  # Eleva para o usuário Administrador
  tasks:
    - name: Executar script Python
      win_shell: python C:\Windows\Temp\script.py
