- name: Coletar chaves do Windows das máquinas
  hosts: windows
  tasks:
    - name: Coletar arquivos gerados
      fetch:
        src: C:\Windows\chave_windows.txt
        dest: /tmp/  # Adicionada barra no final para indicar diretório
        flat: yes  # Mantém apenas os arquivos sem subpastas

- name: Consolidar chaves em um único CSV
  hosts: localhost
  tasks:
    - name: Criar arquivo CSV consolidado
      shell: |
        echo "Nome do Computador;Endereço MAC;Chave do Windows" > /tmp/chaves.csv
        cat /tmp/*.txt >> /tmp/chaves.csv
