---
- name: Executar script Python
  hosts: seus_hosts
  become: true  # Use isso se precisar de permissões elevadas
  tasks:
    - name: Executar script Python
      command: python3 /caminho/do/seu/script.py
