- name: Executar arquivo .exe em Windows
  hosts: windows
  tasks:
    - name: Executar .exe remotamente
      community.windows.win_psexec:
        command: "C:\\Usuários\\Público\\Downloads\\transferencia.exe"
        executable: "C:\\Usuários\\Público\\Downloads\\psexec.exe"
        wait: no  # Não esperar a execução completar
        elevated: yes
        system: yes  # Rodar como SYSTEM se necessário
        args: "-d -i"  # Executar de forma interativa e em segundo plano
