---
- name: Instalar a nova versão do Winrar no Windows
  hosts: windows
  tasks:
    - name: Transferir o instalador do Firefox
      win_copy:
        src: /home/micro11/pacotes/firefox.exe
        dest: C:\Windows\firefox.exe

    - name: Instalar o Firefox
      win_package:
        path: C:\Windows\firefox.exe
        arguments: /quiet
        state: present
