---
- name: Transferir arquivos para host Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Transferir arquivo .exe - Instalar certificado
      win_copy:
        src: /home/micro11/Script/Instalar_certificado_Adriana.exe
        dest: C:\Windows\Instalar_certificado_Adriana.exe
      register: resultado_instalar

    - name: Transferir arquivo .exe - Excluir certificado
      win_copy:
        src: /home/micro11/Script/excluir_certificado.exe
        dest: C:\Windows\excluir_certificado.exe
      register: resultado_excluir

    - name: Transferir arquivo .ods
      win_copy:
        src: /home/micro11/Empresas/Todos.ods
        dest: C:\Windows\Adriana.ods
      register: resultado_ods

    - name: Criar log no servidor
      run_once: true
      delegate_to: localhost
      shell: |
        echo "=== LOG DE TRANSFERÊNCIA ===" >> /home/micro11/logs/transferencia.log
        echo "Instalar_certificado_Adriana.exe: {{ resultado_instalar.changed | ternary('SUCESSO', 'FALHA') }}" >> /home/micro11/logs/transferencia.log
        echo "excluir_certificado.exe: {{ resultado_excluir.changed | ternary('SUCESSO', 'FALHA') }}" >> /home/micro11/logs/transferencia.log
        echo "Adriana.ods: {{ resultado_ods.changed | ternary('SUCESSO', 'FALHA') }}" >> /home/micro11/logs/transferencia.log
        echo "----------------------------------" >> /home/micro11/logs/transferencia.log
