---
- name: Instalar WinRAR, Foxit Reader, Thunderbird e Firefox no Windows
  hosts: windows
  tasks:
    # Transferência dos instaladores
    - name: Transferir o instalador do WinRAR
      win_copy:
        src: /home/micro11/pacotes/winrar-x64-711br.exe
        dest: C:\Windows\Temp\winrar-x64-711br.exe
        
    - name: Transferir o instalador do Foxit Reader
      win_copy:
        src: /home/micro11/pacotes/FoxitPDFReader.exe
        dest: C:\Windows\Temp\FoxitPDFReader.exe

    - name: Transferir o instalador do Thunderbird
      win_copy:
        src: /home/micro11/pacotes/Thunderbird-Setup.exe
        dest: C:\Windows\Temp\Thunderbird-Setup.exe

    - name: Transferir o instalador do Firefox
      win_copy:
        src: /home/micro11/pacotes/Firefox-Installer.exe
        dest: C:\Windows\Temp\Firefox-Installer.exe

    # Instalação dos programas
    - name: Instalar o WinRAR
      win_package:
        path: C:\Windows\Temp\winrar-x64-711br.exe
        arguments: /S
        state: present
        
    - name: Instalar o Foxit Reader
      win_package:
        path: C:\Windows\Temp\FoxitPDFReader.exe
        arguments: /quiet
        state: present

    - name: Instalar o Thunderbird
      win_package:
        path: C:\Windows\Temp\Thunderbird-Setup.exe
        arguments: -ms
        state: present

    - name: Instalar o Firefox
      win_package:
        path: C:\Windows\Temp\Firefox-Installer.exe
        arguments: -ms
        state: present

    # Limpeza dos instaladores após a instalação
    - name: Remover arquivos de instalação
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\Windows\Temp\winrar-x64-711br.exe
        - C:\Windows\Temp\FoxitPDFReader.exe
        - C:\Windows\Temp\Thunderbird-Setup.exe
        - C:\Windows\Temp\Firefox-Installer.exe

# ---
# - name: Instalar a nova versão do Winrar no Windows
#   hosts: windows
#   tasks:
#     - name: Transferir o instalador do Winrar
#       win_copy:
#         src: /home/micro11/pacotes/winrar-x64-711br.exe
#         dest: C:\Windows\winrar-x64-711br.exe

#     - name: Instalar o Winrar
#       win_package:
#         path: C:\Windows\winrar-x64-711br.exe
#         arguments: /quiet
#         state: present
