---
- name: Instalar a nova versão do Winrar no Windows
  hosts: windows
  tasks:
    - name: Transferir o instalador do Winrar
      win_copy:
        src: /home/micro11/pacotes/winrar-x64-711br.exe
        dest: C:\Windows\winrar-x64-711br.exe

    - name: Instalar o Winrar
      win_package:
        path: C:\Windows\winrar-x64-711br.exe
        arguments: /quiet
        state: present
