---
- name: Transferir arquivos para host Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Transferir arquivo .exe - Instalador Certificado
      win_copy:
        src: /home/micro11/Script/Instalar_certificado_Rose.exe
        dest: C:\Windows\Instalar_certificado_Rose.exe
        
    - name: Transferir arquivo .exe - Exclui Certificado
      win_copy:
        src: /home/micro11/Script/excluir_certificado_gerentes.exe
        dest: C:\Windows\excluir_certificado.exe
    
    - name: Transferir arquivo .ods - Planilha Certificado
      win_copy:
        src: /home/micro11/Empresas/Rosenete.ods
        dest: C:\Windows\Rose.ods
