- name: Install an Application with chocolatey
  hosts: all
  tasks:

    - name: Ensure Chocolatey itself is installed
      win_chocolatey:
        name: chocolatey
        state: latest
    - name: Install Wireshark
      win_chocolatey:
        name: wireshark
        state: present
        version: '4.2.3'
    - name: Install multiples packages
      win_chocolatey:
        name:
        - slack
        - zoom
        - filezilla
        state: present
        state: latest
        
