- name: Install an Application with chocolatey
  hosts: all
  tasks:
    - name: Install multiples packages
      win_chocolatey:
        name:
        - foxitreader
        - firefox
        state: latest


# - name: Install an Application with chocolatey
#   hosts: all
#   tasks:

#     - name: Ensure Chocolatey itself is installed
#       win_chocolatey:
#         name: chocolatey
#         state: latest
#     - name: Install Wireshark
#       win_chocolatey:
#         name: wireshark
#         state: present
#     - name: Install multiples packages
#       win_chocolatey:
#         name:
#         - winrar
#         state: latest
